issue_tracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
]

webapp/urls.py
from django.urls import path

from webapp.views.task import TaskDetailView, TaskCreateView, TaskUpdateView, TaskDeleteView
from webapp.views.project import ProjectListView, ProjectDetailView, ProjectCreateView, ProjectUpdateView, ProjectDeleteView

app_name = 'webapp'

urlpatterns = [
    path('', ProjectListView.as_view(), name='project_list'),
    path('project/<int:pk>', ProjectDetailView.as_view(), name='project_detail'),
    path('project/create', ProjectCreateView.as_view(), name='project_create'),
    path('project/<int:pk>/update', ProjectUpdateView.as_view(), name='project_update'),
    path('project/<int:pk>/delete', ProjectDeleteView.as_view(), name='project_delete'),
    path('task/<int:pk>/', TaskDetailView.as_view(), name='task_detail'),
    path('project/<int:pk>/task/create/', TaskCreateView.as_view(), name='task_create'),
    path('task/<int:pk>/update/', TaskUpdateView.as_view(), name='task_update'),
    path('task/<int:pk>/delete/', TaskDeleteView.as_view(), name='task_delete'),
]

webapp/models/base_model.py
from django.db import models


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')

    class Meta:
        abstract = True

webapp/models/project.py
from django.db import models
from django.urls import reverse


class Project(models.Model):
    start_date = models.DateField(verbose_name='Дата начала')
    end_date = models.DateField(blank=True, null=True, verbose_name='Дата окончания')
    name = models.CharField(max_length=100, verbose_name='Название проекта')
    description = models.TextField(blank=True, null=True, verbose_name='Описание')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('webapp:project_detail', kwargs={'pk': self.pk})

webapp/models/status.py
from django.db import models


class Status(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название', unique=True)

    def __str__(self):
        return self.name

webapp/models/task.py
from django.db import models
from webapp.models import BaseModel


class Task(BaseModel):
    title = models.CharField(max_length=100, verbose_name='Заголовок')
    description = models.TextField(verbose_name='Описание', blank=True, null=True)
    status = models.ForeignKey('webapp.Status', on_delete=models.RESTRICT, verbose_name='Статус', related_name='tasks', blank=True, null=True)
    types = models.ManyToManyField('webapp.Type', related_name='tasks', verbose_name='Типы', blank=True)
    project = models.ForeignKey('webapp.Project', on_delete=models.SET_NULL, related_name='tasks', verbose_name='Проект',blank=True, null=True)

    def __str__(self):
        return self.title

webapp/models/type.py
from django.db import models


class Type(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название', unique=True)

    def __str__(self):
        return self.name

webapp/forms.py
from django import forms
from django.core.exceptions import ValidationError

from webapp.models import Task, Status, Type


class TaskForm(forms.ModelForm):

        status = forms.ModelChoiceField(queryset=Status.objects.all(), label='Статус', required=True)
        types = forms.ModelMultipleChoiceField(queryset=Type.objects.all(), label='Тип', required=True)

        class Meta:
            model = Task
            fields = ['title', 'description', 'status', 'types']
            widgets = {
                'title': forms.TextInput(attrs={'class': 'form-control'}),
                'description': forms.Textarea(attrs={'class': 'form-control'}),
                'status': forms.Select(attrs={'class': 'form-select'}),
                'types': forms.CheckboxSelectMultiple(),
            }

        def clean_title(self):
            title = self.cleaned_data.get('title')
            forbidden_words = ['какие-то','запрещенные', 'запрещённые', 'слова']

            if title:
                title_lower = title.lower()
                for word in forbidden_words:
                    if word in title_lower:
                        raise ValidationError(
                            f'Заголовок содержит запрещённое слово: "{word}". '
                        )
            return title

        def clean_description(self):
            description = self.cleaned_data.get('description', '').strip()

            if description and len(description) < 10:
                raise ValidationError('Описание слишком короткое — минимум 10 символов.')

webapp/forms/project.py
from django import forms
from django.core.exceptions import ValidationError

from webapp.models import Project

class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['start_date', 'end_date','name', 'description']
        widgets = {
            'name': forms.TextInput(attrs={'class':'form-control'}),
            'description': forms.Textarea(attrs={'class':'form-control','rows':'4'}),
            'start_date': forms.DateInput(attrs={'class':'form-control', 'type':'date'}),
            'end_date': forms.DateInput(attrs={'class':'form-control', 'type':'date'}),
        }

    def clean(self):
        cleaned_data = super().clean()
        start_date = cleaned_data.get('start_date')
        end_date = cleaned_data.get('end_date')

        if start_date and end_date:
            if end_date < start_date:
                raise ValidationError(
                    "Дата окончания не может быть раньше даты начала проекта."
                )

webapp/forms/search.py
from django import forms

class SearchForm(forms.Form):
    search = forms.CharField(max_length=100, required=False, label='Найти')

webapp/forms/task.py
from django import forms
from django.core.exceptions import ValidationError

from webapp.models import Task, Status, Type


class TaskForm(forms.ModelForm):

        status = forms.ModelChoiceField(queryset=Status.objects.all(), label='Статус', required=True)
        types = forms.ModelMultipleChoiceField(queryset=Type.objects.all(), label='Тип', required=True)

        class Meta:
            model = Task
            fields = ['title', 'description', 'status', 'types']
            widgets = {
                'title': forms.TextInput(attrs={'class': 'form-control'}),
                'description': forms.Textarea(attrs={'class': 'form-control'}),
                'status': forms.Select(attrs={'class': 'form-select'}),
                'types': forms.CheckboxSelectMultiple(),
            }

        def clean_title(self):
            title = self.cleaned_data.get('title')
            forbidden_words = ['какие-то','запрещенные', 'запрещённые', 'слова']

            if title:
                title_lower = title.lower()
                for word in forbidden_words:
                    if word in title_lower:
                        raise ValidationError(
                            f'Заголовок содержит запрещённое слово: "{word}". '
                        )
            return title

        def clean_description(self):
            description = self.cleaned_data.get('description', '').strip()

            if description and len(description) < 10:
                raise ValidationError('Описание слишком короткое — минимум 10 символов.')
            return description

webapp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import TemplateView, View

from webapp.forms import TaskForm
from webapp.models import Task


class TaskListView(TemplateView):
    template_name = 'task/task_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tasks'] = Task.objects.all()
        return context


class TaskDetailView(TemplateView):
    template_name = 'task/task_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['task'] = get_object_or_404(Task, pk=self.kwargs.get('pk'))
        return context


class TaskCreateView(View):

    def get(self, request, *args, **kwargs):
        form = TaskForm()
        return render(request, 'task/task_add.html', {'form': form})

    def post(self, request, *args, **kwargs):
        form = TaskForm(request.POST)
        if form.is_valid():
            task = form.save()
            return redirect('task_detail', pk=task.id)
        else:
            return render(request, 'task/task_add.html', {'form': form})


class TaskUpdateView(View):

    def get(self, request, *args, pk,**kwargs):
        task = get_object_or_404(Task, pk=pk)
        form = TaskForm(instance=task)
        return render(request, 'task/task_update.html', {'form': form})

    def post(self, request, *args, pk, **kwargs):
        task = get_object_or_404(Task, pk=pk)
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            task = form.save()
            return redirect('task_detail', pk=task.id)
        return render(request, 'task/task_update.html', {'form': form, 'task': task})


class TaskDeleteView(View):

    def get(self, request, *args, pk,**kwargs):
        task = get_object_or_404(Task, pk=pk)
        return render(request, 'task/task_delete.html', {'task': task})

    def post(self, request, *args, pk,**kwargs):
        task = get_object_or_404(Task, pk=pk)
        task.delete()
        return redirect('task_list')

webapp/views/project.py
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.utils.http import urlencode
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin

from webapp.forms import SearchForm
from webapp.forms.project import ProjectForm
from webapp.models import Project


class ProjectListView(ListView):
    template_name = 'project/project_list.html'
    model = Project
    context_object_name = 'projects'
    paginate_by = 5

    def dispatch(self, request, *args, **kwargs):
        self.search_form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            queryset = queryset.filter(Q(name__icontains=self.search_value) | Q(description__icontains=self.search_value))
        return queryset

    def get_context_data(self, object_list = None,**kwargs):
        context = super().get_context_data(object_list=object_list,**kwargs)
        context['search_form'] = self.search_form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
            context['search_value'] = self.search_value
        return context

    def get_search_form(self):
        return SearchForm(self.request.GET)

    def get_search_value(self):
        search_value = ''
        if self.search_form.is_valid():
            search_value = self.search_form.cleaned_data.get('search', '')
        return search_value


class ProjectDetailView(DetailView):
    template_name = 'project/project_detail.html'
    model = Project

    def get_context_data(self, **kwargs):
        context = super(ProjectDetailView, self).get_context_data(**kwargs)
        project = self.object
        context['tasks'] = project.tasks.all()
        return context


class ProjectCreateView(LoginRequiredMixin, CreateView):
    template_name = 'project/project_create.html'
    form_class = ProjectForm


class ProjectUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'project/project_update.html'
    form_class = ProjectForm
    model = Project


class ProjectDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'project/project_delete.html'
    model = Project
    success_url = reverse_lazy('webapp:project_list')

webapp/views/task.py
from django.shortcuts import get_object_or_404
from django.views.generic import CreateView, UpdateView, DeleteView, DetailView
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin

from webapp.forms import TaskForm
from webapp.models import Task, Project


class TaskDetailView(DetailView):
    template_name = 'task/task_detail.html'
    model = Task

    def get_context_data(self, **kwargs):
        context = super(TaskDetailView, self).get_context_data(**kwargs)
        return context


class TaskCreateView(LoginRequiredMixin, CreateView):
    template_name = 'task/task_add.html'
    form_class = TaskForm

    def get_success_url(self):
        return reverse('webapp:project_detail', kwargs={'pk': self.object.project.pk})

    def form_valid(self, form):
        project = get_object_or_404(Project, pk=self.kwargs.get('pk'))
        form.instance.project = project
        return super().form_valid(form)


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'task/task_update.html'
    form_class = TaskForm
    model = Task

    def get_success_url(self):
        return reverse('webapp:project_detail', kwargs={'pk': self.object.project.pk})


class TaskDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'task/task_delete.html'
    model = Task

    def get_success_url(self):
        return reverse('webapp:project_detail', kwargs={'pk': self.object.project.pk})

webapp/templates/project/project_create.html
{% extends 'base.html' %}

{% block title %}Создание проекта{% endblock %}

{% block content %}
    <h1>Новый проект!</h1>
    <form method="POST" action="">
        {% include 'partial/base_form.html' with button_name='Создать' %}
    </form>

{% endblock %}

webapp/templates/project/project_delete.html
{% extends 'base.html' %}

{% block title %}{% endblock %}

{% block content %}
    <h1>Удаление проекта</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <p>Вы действительно хотите удалить проект "{{ project.name }}"?</p>
        <button type="submit" class="btn btn-danger">Да</button>
        <a href="{% url 'webapp:project_detail' project.id %}" class="btn btn-secondary">Нет</a>
    </form>
{% endblock %}

webapp/templates/project/project_detail.html
{% extends 'base.html' %}

{% block title %}Project {{ project.id }}{% endblock %}

{% block content %}
    <div class="card text-bg-primary mb-3">
      <div class="card-body">
        <h5 class="card-title">Проект: {{ project.name }}</h5>

        {% if project.description %}
            <p class="card-text"><strong>Описание:</strong> <br>{{ project.description }}</p>
        {% else %}
            <p class="card-text">Без описания</p>
        {% endif %}
        <p class="card-text">Дата начала проекта: {{ project.start_date}}</p>
        {% if project.end_date %}
            <p class="card-text">Дата окончания проекта: {{ project.end_date }}</p>
        {% else %}
            <p class="card-text">Сроки проекта не указаны</p>
        {% endif %}
        {% if user.is_authenticated %}
            <a href="{% url 'webapp:project_update' pk=project.id %}" class="btn btn-outline-light btn-sm mb-2">Изменить проект</a>
            <a href="{% url 'webapp:project_delete' pk=project.id %}" class="btn btn-outline-light btn-sm mb-2">Удалить проект</a>
            <a href="{% url 'webapp:task_create' project.id %}" class="btn btn-outline-light btn-sm mb-2">Добавить задачу</a>
        {% endif %}
      </div>
    </div>

    <h4 class="mb-3">Задачи</h4>
    <div class="row row-cols-2 row-cols-md-3">
        {% for task in tasks %}
            <div class="col mb-3">
                <div class="card h-100">
                    <div class="card-body">
                        <h5 class="card-title">{{ task.title }}</h5>
                        <p class="card-text"><strong>Статус: </strong>{{ task.status }}</p>
                        <p class="card-text"><strong>Тип: </strong>
                            {% for type in task.types.all %}
                                <span class="card-text">{{ type }}</span>
                            {% empty %}
                                <span class="card-text">—</span>
                            {% endfor %}
                        </p>
                        <a href="{% url 'webapp:task_detail' pk=task.id %}" class="btn btn-primary btn-sm mb-2">Подробнее...</a>
                        {% if user.is_authenticated %}
                            <a href="{% url 'webapp:task_update' pk=task.id %}" class="btn btn-primary btn-sm mb-2">Изменить задачу</a>
                            <a href="{% url 'webapp:task_delete' pk=task.id %}" class="btn btn-primary btn-sm mb-2">Удалить задачу</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% empty %}
            <p>Задач нет.</p>
        {% endfor %}
    </div>


{% endblock %}

webapp/templates/project/project_list.html
{% extends 'base.html' %}

{% block title %}Проекты{% endblock %}

{% block content %}
    <h1 class="mb-3">Список проектов</h1>
    {% include 'partial/search.html' with form=search_form %}
    {% if projects %}
        <div class="row row-cols row-cols-md-4">
            {% for project in projects %}
                <div class="col my-3">
                    <div class="card h-100">
                        <div class="card-body">
                            <h5 class="card-title">{{ project.name }}</h5>
                            {% if project.end_date %}
                                <p class="card-text">Дата окончания проекта: {{ project.end_date }}</p>
                            {% else %}
                                <p class="card-text">Сроки проекта не указаны</p>
                            {% endif %}
                            <a href="{% url 'webapp:project_detail' pk=project.id %}" class="btn btn-primary btn-sm">Подробнее...</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

        {% if is_paginated %}
            {% include 'partial/pagination.html' %}
        {% endif %}
    {% else %}
        <h1 class="display-1 mt-5">Проекты не найдены!</h1>
    {% endif %}

{% endblock %}

webapp/templates/project/project_update.html
{% extends 'base.html' %}

{% block title %}Редактирование проекта{% endblock %}

{% block content %}
    <h1>Редактирование проекта!</h1>
    <form method="POST" action="">
        {% include 'partial/base_form.html' with button_name='Обновить' %}
    </form>

{% endblock %}